### ISSUE TITLE
The sensor on the robot anymal_b does not publish “/os_cloud_node/imu” information, only “/os_cloud_node/points” information

### ISSUE THREAD

**Issue by chenweigu** [engcang/TROT-Q#3]
The sensor on the robot anymal_b does not publish “/os_cloud_node/imu” information, only “/os_cloud_node/points” information, causing the “laserMapping” node to fail to work normally. Some topics in “rostopic list”(after running "gazebo.launch"):
/joint_states
/joy
/joy/set_feedback
/os_cloud_node/points
/rosout
/rosout_agg
/tf
/tf_static

**Comment by engcang** [comment]
Hi @chenweigu .

You need to install `hector-gazebo-plugins` by `sudo apt install ros-melodic-hector-gazebo-plugins` or `sudo apt install ros-noetic-hector-gazebo-plugins`.

Let me add this in the README also. Thanks for letting me know.

**Comment by chenweigu** [comment]
Thank you, I solved it yesterday, thanks for&nbsp;your&nbsp;letter.




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "engcang/TROT-Q"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年4月25日(星期二) 下午2:16
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [engcang/TROT-Q] The sensor on the robot anymal_b does not publish “/os_cloud_node/imu” information, only “/os_cloud_node/points” information (Issue #3)





 
Hi @chenweigu .
 
You need to install hector-gazebo-plugins by sudo apt install ros-melodic-hector-gazebo-plugins or sudo apt install ros-noetic-hector-gazebo-plugins.
 
Let me add this in the README also. Thanks for letting me know.
